name: pylbm_ui
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pylbm>=0.6
  - ipyvuetify
  - ipympl
  - matplotlib
  - pydantic
  - scipy
  - jupyterlab
  - pathos
  - scikit-optimize
  - nodejs
  - plotly
  - voila
